import {
  ColorSchemeScript,
  Container,
  MantineProvider,
  mantineHtmlProps,
  Stack,
} from "@mantine/core";
import { Frame } from "@/components/Frame";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Text } from "@/components/Text";

const donguriDuel = localFont({
  src: "../assets/fonts/x10y12pxDonguriDuel.ttf",
  variable: "--font-donguri-duel",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${donguriDuel.variable}`}>
        <MantineProvider>
          <Container size="md" py="xl">
            <Stack align="center" gap="xl">
              <Frame>{children}</Frame>
              <Text size="md">@2025 Color Pick Battler</Text>
            </Stack>
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
